---
platform: linux
image_resource:
  type: docker-image
  source:
    repository: splatform/base-ci
    tag: kubecf
inputs:
- name: ci
- name: build-image-resource
- name: kubecf
outputs:
- name: buildpacks_to_be_built
params:
  RELEASES_YAML: ~
  KUBECF_VALUES_YAML: ~
run:
  path: ci/.concourse/suse-buildpacks-ci/stemcell-version-bump/tasks/prep.py
